In [9]:
import pandas as pd

# Read combined CSV files

sdg3_combined_df = pd.read_csv(
    "Raw_Data/SDG_3_Good_Health_and_Well-Being/sdg3_combined.csv"
)

sdg6_combined_df = pd.read_csv(
    "Raw_Data/SDG_6_Clean_Water_and_Sanitation/sdg6_combined.csv"
)

sdg11_combined_df = pd.read_csv(
    "Raw_Data/SDG_11_Sustainable_Cities_and_Communities/sdg11_combined.csv"
)


# Display heads

print("SDG 3 Combined Dataset")
display(sdg3_combined_df.head())

print("SDG 6 Combined Dataset")
display(sdg6_combined_df.head())

print("SDG 11 Combined Dataset")
display(sdg11_combined_df.head())

SDG 3 Combined Dataset

,GeoAreaName,InfantMortality_2030_Predicted,DiseaseMortality_2030_Predicted,SuicideMortality_2030_Predicted
0,Afghanistan,37.457082,28.517287,3.145842
1,Albania,5.546873,4.123085,0.537856
2,Algeria,15.713803,10.728556,1.129431
3,Andorra,1.295250,0.000000,0.000000
4,Angola,12.002988,22.855689,7.281947

SDG 6 Combined Dataset

,GeoAreaName,Stress_2030_Predicted,DrinkingWater_2030_Predicted,Handwashing_2030_Predicted
0,Afghanistan,54.760000,35.766557,56.782834
1,Albania,2.836051,79.785542,0.000000
2,Algeria,175.482805,69.398306,85.653658
3,American Samoa,0.000000,92.731402,0.000000
4,Andorra,11.443845,90.639996,0.000000

SDG 11 Combined Dataset

   GeoAreaName  SlumPopulation_2030_Predicted  DisasterAffected_2030_Predicted
0  Afghanistan                      75.339061                      1609.393514
1      Albania                      -5.932409                       902.918922
2      Algeria                       5.469330                       231.992181
3      Andorra                       0.000000                       -24.487979
4       Angola                      81.406761                       119.414922

In [10]:
# Merge all SDG datasets using only matching GeoAreaName values

final_combined_df = (
    sdg3_combined_df
    .merge(sdg6_combined_df, on="GeoAreaName", how="inner")
    .merge(sdg11_combined_df, on="GeoAreaName", how="inner")
)

# Display result
print("Final Combined Dataset Shape:", final_combined_df.shape)

display(final_combined_df)

Final Combined Dataset Shape: (200, 9)

,GeoAreaName,InfantMortality_2030_Predicted,DiseaseMortality_2030_Predicted,SuicideMortality_2030_Predicted,Stress_2030_Predicted,DrinkingWater_2030_Predicted,Handwashing_2030_Predicted,SlumPopulation_2030_Predicted,DisasterAffected_2030_Predicted
0,Afghanistan,37.457082,28.517287,3.145842,54.760000,35.766557,56.782834,75.339061,1609.393514
1,Albania,5.546873,4.123085,0.537856,2.836051,79.785542,0.000000,-5.932409,902.918922
2,Algeria,15.713803,10.728556,1.129431,175.482805,69.398306,85.653658,5.469330,231.992181
3,Andorra,1.295250,0.000000,0.000000,11.443845,90.639996,0.000000,0.000000,-24.487979
4,Angola,12.002988,22.855689,7.281947,1.870000,0.000000,37.643818,81.406761,119.414922
...,...,...,...,...,...,...,...,...,...
195,Viet Nam,10.267658,19.265208,7.793217,17.553621,61.855982,90.606391,35.549101,-0.126799
196,World,0.000000,15.644420,7.499344,17.541811,76.607072,84.120878,22.081276,0.000000
197,Yemen,24.906752,24.719147,3.306455,311.829231,0.000000,68.580315,37.762881,-2556.458024
198,Zambia,23.839560,23.789934,6.785777,10.861360,0.000000,18.842607,42.997446,4141.474159
199,Zimbabwe,50.200582,34.145514,17.970350,49.610159,24.036961,42.378811,73.246789,76108.155012