# Sustainable Development Goal 3: Good Health and Well-Being

This Jupyter Notebook focuses on the development and preparation of the SDG 3 Sub-Index, which relates to the United Nations Sustainable Development Goal 3: Good Health and Well-Being.

The purpose of this notebook is to import, inspect, clean, and prepare datasets associated with health and well-being indicators for use in a larger composite indicator project. The processed data will later contribute towards calculating a comparative SDG readiness score across countries.

The following datasets are obtained through: https://unstats.un.org/sdgs/dataportal/ 

**Disclaimer: This dataset has already been standardised by the UN SDG database, therefore some common data cleaning steps such as formatting corrections, unit conversions, and major transformations were not required. The cleaning process mainly focused on handling missing values, identifying duplicates, selecting relevant indicators and preparing the data for analysis.**

### 1.1 Import Data

In [9]:
# Import pandas
import pandas as pd

# Load datasets
infant_df = pd.read_excel("SH_DYN_IMRT.xlsx")
disease_df = pd.read_excel("SH_DTH_NCOM.xlsx")
suicide_df = pd.read_excel("SH_STA_SCIDE.xlsx")

# Display first 5 rows of each dataframe
print("Infant Mortality Dataset:")
display(infant_df.head())

print("\nNon-Communicable Diseases Dataset:")
display(disease_df.head())

print("\nSuicide Rates Dataset:")
display(suicide_df.head())

Infant Mortality Dataset:

,Goal,Target,Indicator,SeriesCode,SeriesDescription,GeoAreaCode,GeoAreaName,Age,Reporting Type,Sex,...,2015,2016,2017,2018,2019,2020,2021,2022,2023,2024
0,3,3.2,3.2.1,SH_DYN_IMRT,"Infant mortality rate (deaths per 1,000 live b...",4,Afghanistan,<1Y,G,BOTHSEX,...,63.996677,61.947529,60.088528,58.278091,56.566551,54.891174,53.229991,51.569272,49.925945,48.314751
1,3,3.2,3.2.1,SH_DYN_IMRT,"Infant mortality rate (deaths per 1,000 live b...",4,Afghanistan,<1Y,G,FEMALE,...,59.647728,57.719111,55.862142,54.032447,52.407673,50.766454,49.148406,47.587932,46.041698,44.467931
2,3,3.2,3.2.1,SH_DYN_IMRT,"Infant mortality rate (deaths per 1,000 live b...",4,Afghanistan,<1Y,G,MALE,...,68.074908,65.979756,64.066914,62.226421,60.444564,58.751690,57.006363,55.297601,53.609533,51.994949
3,3,3.2,3.2.1,SH_DYN_IMRT,"Infant mortality rate (deaths per 1,000 live b...",8,Albania,<1Y,G,BOTHSEX,...,7.640828,7.626143,7.702629,7.831172,7.983395,8.134492,8.253567,8.320401,8.317321,8.251787
4,3,3.2,3.2.1,SH_DYN_IMRT,"Infant mortality rate (deaths per 1,000 live b...",8,Albania,<1Y,G,FEMALE,...,6.807895,6.818138,6.899222,7.010023,7.144995,7.279020,7.392719,7.453925,7.454765,7.386894

Non-Communicable Diseases Dataset:

,Goal,Target,Indicator,SeriesCode,SeriesDescription,GeoAreaCode,GeoAreaName,Age,Name of non-communicable disease,Reporting Type,Sex,Units,2000,2005,2010,2015,2019,2020,2021
0,3,3.4,3.4.1,SH_DTH_NCOM,Mortality rate attributed to cardiovascular di...,4,Afghanistan,30-69,NaN,G,BOTHSEX,PERCENT,43.2,41.9,37.6,35.0,34.4,34.8,32.7
1,3,3.4,3.4.1,SH_DTH_NCOM,Mortality rate attributed to cardiovascular di...,4,Afghanistan,30-69,NaN,G,FEMALE,PERCENT,40.0,39.9,36.1,34.1,34.2,34.3,33.5
2,3,3.4,3.4.1,SH_DTH_NCOM,Mortality rate attributed to cardiovascular di...,4,Afghanistan,30-69,NaN,G,MALE,PERCENT,46.7,44.1,39.4,36.0,34.7,35.3,31.5
3,3,3.4,3.4.1,SH_DTH_NCOM,Mortality rate attributed to cardiovascular di...,8,Albania,30-69,NaN,G,BOTHSEX,PERCENT,18.0,19.4,18.9,13.3,11.3,10.4,10.0
4,3,3.4,3.4.1,SH_DTH_NCOM,Mortality rate attributed to cardiovascular di...,8,Albania,30-69,NaN,G,FEMALE,PERCENT,12.3,13.6,16.2,9.6,5.8,4.4,7.3

Suicide Rates Dataset:

,Goal,Target,Indicator,SeriesCode,SeriesDescription,GeoAreaCode,GeoAreaName,Reporting Type,Sex,Units,2000,2005,2010,2015,2019,2020,2021
0,3,3.4,3.4.2,SH_STA_SCIDE,"Suicide mortality rate, by sex (deaths per 100...",4,Afghanistan,G,BOTHSEX,PER_100000_POP,4.4,4.2,3.6,3.5,3.5,3.5,3.6
1,3,3.4,3.4.2,SH_STA_SCIDE,"Suicide mortality rate, by sex (deaths per 100...",4,Afghanistan,G,FEMALE,PER_100000_POP,2.9,2.8,2.1,2.1,2.4,2.4,2.4
2,3,3.4,3.4.2,SH_STA_SCIDE,"Suicide mortality rate, by sex (deaths per 100...",4,Afghanistan,G,MALE,PER_100000_POP,5.8,5.5,5.0,4.8,4.7,4.6,4.8
3,3,3.4,3.4.2,SH_STA_SCIDE,"Suicide mortality rate, by sex (deaths per 100...",8,Albania,G,BOTHSEX,PER_100000_POP,4.8,6.8,6.8,4.1,3.8,3.4,2.8
4,3,3.4,3.4.2,SH_STA_SCIDE,"Suicide mortality rate, by sex (deaths per 100...",8,Albania,G,FEMALE,PER_100000_POP,3.3,5.3,5.8,3.2,2.7,2.3,2.3

#### Meaning of Datasets

- infant_df : Infant mortality rate (deaths per 1,000 live births) SH_DYN_IMRT
- disease_df : Mortality rate attributed to cardiovascular disease, cancer, diabetes or chronic respiratory disease (probability) SH_DTH_NCOM
- suicide_df : Suicide mortality rate, by sex (deaths per 100,000 population) SH_STA_SCIDE

### 2.1 Select Columns

In [10]:
# Select columns for each dataset

# Years
years_2000_2024 = [str(year) for year in range(2000, 2025)]

# Clean column names
infant_df.columns = infant_df.columns.str.strip()
disease_df.columns = disease_df.columns.str.strip()
suicide_df.columns = suicide_df.columns.str.strip()

# Select only years that exist in each dataset
infant_years = [year for year in years_2000_2024 if year in infant_df.columns]
disease_years = [year for year in years_2000_2024 if year in disease_df.columns]
suicide_years = [year for year in years_2000_2024 if year in suicide_df.columns]

infant_df = infant_df[['GeoAreaName', 'Sex'] + infant_years]
disease_df = disease_df[['GeoAreaName', 'Sex'] + disease_years]
suicide_df = suicide_df[['GeoAreaName', 'Sex'] + suicide_years]

# Display first 5 rows
print("Infant Dataset:")
display(infant_df.head())

print("\nDisease Dataset:")
display(disease_df.head())

print("\nSuicide Dataset:")
display(suicide_df.head())

Infant Dataset:

,GeoAreaName,Sex,2000,2001,2002,2003,2004,2005,2006,2007,...,2015,2016,2017,2018,2019,2020,2021,2022,2023,2024
0,Afghanistan,BOTHSEX,110.603976,107.512739,104.260840,100.837861,97.362781,93.791289,90.283571,86.794386,...,63.996677,61.947529,60.088528,58.278091,56.566551,54.891174,53.229991,51.569272,49.925945,48.314751
1,Afghanistan,FEMALE,105.029623,102.201298,99.230908,95.846897,92.363152,88.861964,85.418372,82.029893,...,59.647728,57.719111,55.862142,54.032447,52.407673,50.766454,49.148406,47.587932,46.041698,44.467931
2,Afghanistan,MALE,116.029132,112.588324,109.043027,105.607188,102.143482,98.460371,94.899527,91.308474,...,68.074908,65.979756,64.066914,62.226421,60.444564,58.751690,57.006363,55.297601,53.609533,51.994949
3,Albania,BOTHSEX,17.798590,16.951080,16.098606,15.248784,14.388305,13.525847,12.674911,11.855992,...,7.640828,7.626143,7.702629,7.831172,7.983395,8.134492,8.253567,8.320401,8.317321,8.251787
4,Albania,FEMALE,14.905698,14.166050,13.425607,12.690549,11.965510,11.212410,10.560447,9.961517,...,6.807895,6.818138,6.899222,7.010023,7.144995,7.279020,7.392719,7.453925,7.454765,7.386894

Disease Dataset:

   GeoAreaName      Sex  2000  2005  2010  2015  2019  2020  2021
0  Afghanistan  BOTHSEX  43.2  41.9  37.6  35.0  34.4  34.8  32.7
1  Afghanistan   FEMALE  40.0  39.9  36.1  34.1  34.2  34.3  33.5
2  Afghanistan     MALE  46.7  44.1  39.4  36.0  34.7  35.3  31.5
3      Albania  BOTHSEX  18.0  19.4  18.9  13.3  11.3  10.4  10.0
4      Albania   FEMALE  12.3  13.6  16.2   9.6   5.8   4.4   7.3

Suicide Dataset:

   GeoAreaName      Sex  2000  2005  2010  2015  2019  2020  2021
0  Afghanistan  BOTHSEX   4.4   4.2   3.6   3.5   3.5   3.5   3.6
1  Afghanistan   FEMALE   2.9   2.8   2.1   2.1   2.4   2.4   2.4
2  Afghanistan     MALE   5.8   5.5   5.0   4.8   4.7   4.6   4.8
3      Albania  BOTHSEX   4.8   6.8   6.8   4.1   3.8   3.4   2.8
4      Albania   FEMALE   3.3   5.3   5.8   3.2   2.7   2.3   2.3

#### 2.2 Selection of Columns

At this stage, only the variables required for the **SDG 3 sub-index analysis** are retained from each dataset.

The selection keeps:

* all countries available within the datasets,
* identifying columns such as `GeoAreaName` and `Sex`,
* yearly health indicator values from 2000 up to the most recent year available within each dataset.

For the SDG 3 sub-index, the selected datasets include infant mortality, disease-related indicators, and suicide mortality indicators.

### 3.1 Dealing with Duplicates

#### infant_df

#### disease_df

#### suicide_df